name: Build and test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v4
    - name: Use Node.js version 20
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Display my name 
      run: echo nikolay_manchev
    - name: Install dependencies
      run: npm install
    - name: Run Unit tests
      run: npm run test:unit
    - name: Run the app
      run: npm start &
    - name: Install Playwright browsers
      run: npx playwright install
    - name: Run Ui tests
      run: npm run test:ui
